Yardev
Yar-ua/stud_framework pull request #2
Opened 2018-04-09 21:35 UTC by Yar-ua

Implemented CRUD methods for model

2018-04-10 11:19 UTC, ddavidov requested changes
Check comments plz.

2018-04-10 11:19 UTC, ddavidov commented on src/Models/Model.php
> +            return 'Insert to DB was successfully!';
А если нет?

2018-04-10 11:19 UTC, ddavidov commented on src/Models/Model.php
> +            return 'Update to DB was successfully!';
Предлагаю сделать результат boolean. TRUE в случае успешной операции и FALSE или исключение в противном случае. Иначе, как нам в Контроллере понимать, что операция прошла успешно? искать подстроку '/success/' в возвращаемой строке? :)

2018-04-10 11:19 UTC, ddavidov commented on src/Models/Model.php
> +        };
То же самое.

2018-04-10 11:19 UTC, ddavidov commented on src/Models/Model.php
> +            array_push($values, "'" . $value . "'");
Тут, пока оставим так, но возможно это будет работать не для всех типов вставляемых данных...

2018-04-12 01:23 UTC, Yar-ua commented on src/Models/Model.php
> +            return 'Update to DB was successfully!';
логично, заменяю на true

2018-04-12 01:23 UTC, Yar-ua commented on src/Models/Model.php
> +        };
меняю на true

2018-04-12 01:24 UTC, Yar-ua commented on src/Models/Model.php
> +            array_push($values, "'" . $value . "'");
сделаю экранирование и уйду от этой функции...

2018-04-12 01:29 UTC, Yar-ua commented on src/Models/Model.php
> +            return 'Insert to DB was successfully!';
А как лучше сделать, возвращать в случае успешной вставки true? или нужно еще добавить Exception в случае неудачной вставки?

2018-04-12 13:28 UTC, ddavidov commented
Хорошо. Если протестил и работает, можно сливать. Кому ставить плюсик, в какую команду?

2018-04-13 11:24 UTC, Yar-ua commented
Голубков Ярослав и Иванов Александр. Команда без названия.

чт, 12 апр. 2018 г., 16:28 Dmitry Davidov <notifications@github.com>:

> Хорошо. Если протестил и работает, можно сливать. Кому ставить плюсик, в
> какую команду?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Yar-ua/stud_framework/pull/2#issuecomment-380804997>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASsvafVfvDrFpEfo0dzRrUHSSWwULvuwks5tn1Z6gaJpZM4TNQ9K>
> .
>

2018-04-13 20:06 UTC, merged