create register and logout methods, update login method
Yar-ua/stud_framework pull request #3
Opened 2018-04-26 21:37 UTC by Yar-ua

Добавлены методы register, logout, обновлен метод login для аутентификации.
Работа с БД реализована через методы базовой модели Model.

2018-04-27 13:05 UTC, ddavidov requested changes
В целом очень неплохо.

2018-04-27 13:05 UTC, ddavidov commented on src/Controllers/UserController.php
> +        $user = new UserModel($dbo);
Ммм, а $model нам тут не подойдёт часом?

2018-04-27 13:05 UTC, ddavidov commented on src/Controllers/UserController.php
> +        if (empty($request->get('role', '', 'string'))) {
Я бы не позволял ставить пользователю роль из запроса. А просто ставил по умолчанию дефолтную - user и всё.

2018-04-27 13:05 UTC, ddavidov commented on src/Controllers/UserController.php
>          return $user->token;
Это чтобы сразу можно было залогинить зарегистрировавшегося пользователя, так?

2018-04-27 13:05 UTC, ddavidov commented on src/Controllers/UserController.php
> +        $user = $model->findByToken($request->getHeader('X-Auth'));
А это не нужно., просто роут для logouta сделай только для зарегистрированных пользователей.
```
...
'acl' => ['user','admin'],
...
```
 Плюс, если запрос у тебя дошёл сюда, то он уже проходил через Auth middleware, а если так, то юзера текущего можно сразу взять из AuthService::getUser() ага?

2018-04-27 13:05 UTC, ddavidov commented on src/Models/UserModel.php
> +        return parent::create($data);
Ну, в таком случае этот метод вообще не нужно тут объявлять, он наследуется.

2018-04-27 13:05 UTC, ddavidov commented on src/Models/UserModel.php
> +    }
То же самое

2018-04-27 13:24 UTC, Yar-ua commented on src/Controllers/UserController.php
>          return $user->token;
Если логинится зарегистрированный пользователь (имя и пароль в БД совпадают) то генерируем новый токен, сохраняем в БД и отдаем токен на фронт

2018-04-27 13:31 UTC, Yar-ua commented on src/Models/UserModel.php
> +        return parent::create($data);
ок, откорректирую

2018-04-27 13:31 UTC, Yar-ua commented on src/Models/UserModel.php
> +    }
ок, откорректирую

2018-04-27 13:33 UTC, Yar-ua commented on src/Controllers/UserController.php
> +        $user = $model->findByToken($request->getHeader('X-Auth'));
да, верно

2018-04-30 08:04 UTC, ddavidov commented on src/Controllers/UserController.php
>          return $user->token;
Тут немного непонятненько...)

2018-05-01 19:30 UTC, Yar-ua commented on src/Controllers/UserController.php
> +        $user = new UserModel($dbo);
в принципе тоже подойдет

2018-05-01 19:43 UTC, Yar-ua commented on src/Controllers/UserController.php
>          return $user->token;
У меня в фреймворке соглашение - данные для сохранения или изменения должны прийти в виде хеша, где ключи - это имена столбцов таблицы. Так реализовано в моей базовой Model и далее я этого придерживаюсь. в строке $data = array('token' => $user->token) я готовлю хеш для передачи в метод save

2018-05-02 09:36 UTC, ddavidov commented on src/Controllers/UserController.php
>          return $user->token;
Та я немного не о том, ну ок.)

2018-05-02 17:02 UTC, merged